# Generated by Django 2.0.1 on 2018-01-05 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('idsucursal', models.BigIntegerField(primary_key=True, serialize=False)),
                ('horaapertura', models.DateTimeField(blank=True, null=True)),
                ('horacierre', models.DateTimeField(blank=True, null=True)),
                ('municipio', models.CharField(blank=True, max_length=100, null=True)),
                ('colonia', models.CharField(blank=True, max_length=100, null=True)),
                ('calle', models.CharField(blank=True, max_length=100, null=True)),
                ('cp', models.IntegerField(blank=True, null=True)),
                ('numinterior', models.BigIntegerField(blank=True, null=True)),
                ('numexterior', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'sucursal',
                'managed': True,
            },
        ),
    ]
