# Generated by Django 2.0.1 on 2018-01-05 04:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('taquiclave', models.BigIntegerField(primary_key=True, serialize=False)),
                ('email', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('nombre', models.CharField(blank=True, max_length=50, null=True)),
                ('apellidopaterno', models.CharField(blank=True, max_length=50, null=True)),
                ('apellidomaterno', models.CharField(blank=True, max_length=50, null=True)),
                ('municipio', models.CharField(blank=True, max_length=100, null=True)),
                ('colonia', models.CharField(blank=True, max_length=100, null=True)),
                ('calle', models.CharField(blank=True, max_length=100, null=True)),
                ('cp', models.IntegerField(blank=True, null=True)),
                ('numinterior', models.BigIntegerField(blank=True, null=True)),
                ('numexterior', models.BigIntegerField(blank=True, null=True)),
                ('fechaprimervista', models.DateField(blank=True, null=True)),
                ('numpuntos', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'cliente',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Contener',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'contener',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cpedocliente',
            fields=[
                ('cp', models.IntegerField(primary_key=True, serialize=False)),
                ('estado', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'cpedocliente',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cpedoempleado',
            fields=[
                ('cp', models.IntegerField(primary_key=True, serialize=False)),
                ('estado', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'cpedoempleado',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cpedoproveedor',
            fields=[
                ('cp', models.IntegerField(primary_key=True, serialize=False)),
                ('estado', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'cpedoproveedor',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cpedosucursal',
            fields=[
                ('cp', models.IntegerField(primary_key=True, serialize=False)),
                ('estado', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'cpedosucursal',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Curpfnacemp',
            fields=[
                ('curp', models.BigIntegerField(primary_key=True, serialize=False)),
                ('fechanac', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'curpfnacemp',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Dirigir',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechainicio', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'dirigir',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('taquiclave', models.BigIntegerField(primary_key=True, serialize=False)),
                ('salario', models.FloatField(blank=True, null=True)),
                ('email', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('nombre', models.CharField(blank=True, max_length=50, null=True)),
                ('apellidopaterno', models.CharField(blank=True, max_length=50, null=True)),
                ('apellidomaterno', models.CharField(blank=True, max_length=50, null=True)),
                ('municipio', models.CharField(blank=True, max_length=100, null=True)),
                ('colonia', models.CharField(blank=True, max_length=100, null=True)),
                ('calle', models.CharField(blank=True, max_length=100, null=True)),
                ('cp', models.IntegerField(blank=True, null=True)),
                ('numinterior', models.BigIntegerField(blank=True, null=True)),
                ('numexterior', models.BigIntegerField(blank=True, null=True)),
                ('curp', models.BigIntegerField(blank=True, null=True)),
                ('rfc', models.CharField(blank=True, max_length=13, null=True)),
                ('tipo', models.CharField(blank=True, max_length=40, null=True)),
                ('tiposangre', models.CharField(blank=True, max_length=5, null=True)),
                ('numemergencia', models.CharField(blank=True, max_length=20, null=True)),
                ('fechacontratacion', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'empleado',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Fechapedpromo',
            fields=[
                ('fechapedido', models.DateField(primary_key=True, serialize=False)),
                ('promocion', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'fechapedpromo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Historico',
            fields=[
                ('idhistorico', models.BigIntegerField(primary_key=True, serialize=False)),
                ('fechaactualizacion', models.DateField(blank=True, null=True)),
                ('precionuevo', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'historico',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ingrediente',
            fields=[
                ('idingrediente', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=50, null=True)),
                ('marca', models.CharField(blank=True, max_length=60, null=True)),
                ('cantidadexistencia', models.FloatField(blank=True, null=True)),
                ('fechacaducidad', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ingrediente',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Llevar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'llevar',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Mobiliario',
            fields=[
                ('idmueble', models.BigIntegerField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'mobiliario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('numpedido', models.BigIntegerField(primary_key=True, serialize=False)),
                ('fechapedido', models.DateField(blank=True, null=True)),
                ('metodopago', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'pedido',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Poseer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'poseer',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Prodhist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precioprevio', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'prodhist',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('idproducto', models.BigIntegerField(primary_key=True, serialize=False)),
                ('puntosotorgar', models.BigIntegerField(blank=True, null=True)),
                ('nombre', models.CharField(blank=True, max_length=70, null=True)),
                ('precio', models.FloatField(blank=True, null=True)),
                ('taquegoria', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'producto',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Productoleyenda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leyenda', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'productoleyenda',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('rfc', models.CharField(max_length=13, primary_key=True, serialize=False)),
                ('razonsocial', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('iniciorelacion', models.DateField(blank=True, null=True)),
                ('email', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('municipio', models.CharField(blank=True, max_length=100, null=True)),
                ('colonia', models.CharField(blank=True, max_length=100, null=True)),
                ('calle', models.CharField(blank=True, max_length=100, null=True)),
                ('cp', models.IntegerField(blank=True, null=True)),
                ('numinterior', models.BigIntegerField(blank=True, null=True)),
                ('numexterior', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'proveedor',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Proveering',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'proveering',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Proveermob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'proveermob',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Recomendar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'recomendar',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('idsucursal', models.BigIntegerField(primary_key=True, serialize=False)),
                ('horaapertura', models.DateTimeField(blank=True, null=True)),
                ('horacierre', models.DateTimeField(blank=True, null=True)),
                ('municipio', models.CharField(blank=True, max_length=100, null=True)),
                ('colonia', models.CharField(blank=True, max_length=100, null=True)),
                ('calle', models.CharField(blank=True, max_length=100, null=True)),
                ('cp', models.IntegerField(blank=True, null=True)),
                ('numinterior', models.BigIntegerField(blank=True, null=True)),
                ('numexterior', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'sucursal',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tener',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tener',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Transporte',
            fields=[
                ('idtransporte', models.BigIntegerField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(blank=True, max_length=50, null=True)),
                ('marca', models.CharField(blank=True, max_length=55, null=True)),
                ('modelo', models.CharField(blank=True, max_length=70, null=True)),
            ],
            options={
                'db_table': 'transporte',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Conservar',
            fields=[
                ('idproducto', models.ForeignKey(db_column='idproducto', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='inicio.Producto')),
            ],
            options={
                'db_table': 'conservar',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Salsa',
            fields=[
                ('idproducto', models.ForeignKey(db_column='idproducto', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='inicio.Producto')),
                ('nombre', models.CharField(blank=True, max_length=50, null=True)),
                ('presentacion', models.CharField(blank=True, max_length=70, null=True)),
                ('scoville', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'salsa',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sucursaltelefono',
            fields=[
                ('idsucursal', models.ForeignKey(db_column='idsucursal', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='inicio.Sucursal')),
                ('telefono', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'sucursaltelefono',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tacorider',
            fields=[
                ('taquiclave', models.ForeignKey(db_column='taquiclave', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='inicio.Empleado')),
                ('estadisponible', models.NullBooleanField()),
            ],
            options={
                'db_table': 'tacorider',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Licencia',
            fields=[
                ('taquiclave', models.ForeignKey(db_column='taquiclave', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='inicio.Tacorider')),
                ('codigo', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'licencia',
                'managed': False,
            },
        ),
    ]
