# Generated by Django 2.0.1 on 2018-01-08 04:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cpedosucursal',
            fields=[
                ('cp', models.IntegerField(primary_key=True, serialize=False)),
                ('estado', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'cpedosucursal',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('idsucursal', models.BigIntegerField(primary_key=True, serialize=False)),
                ('horaapertura', models.DateTimeField(blank=True, null=True)),
                ('horacierre', models.DateTimeField(blank=True, null=True)),
                ('municipio', models.CharField(blank=True, max_length=100, null=True)),
                ('colonia', models.CharField(blank=True, max_length=100, null=True)),
                ('calle', models.CharField(blank=True, max_length=100, null=True)),
                ('numinterior', models.BigIntegerField(blank=True, null=True)),
                ('numexterior', models.BigIntegerField(blank=True, null=True)),
                ('cp', models.ForeignKey(db_column='cp', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='inicio.Cpedosucursal')),
            ],
            options={
                'db_table': 'sucursal',
                'managed': True,
            },
        ),
    ]
