# Generated by Django 2.0.1 on 2018-01-08 04:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sucursaltelefono',
            fields=[
                ('idsucursal', models.ForeignKey(db_column='idsucursal', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='inicio.Sucursal')),
                ('telefono', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'sucursaltelefono',
                'managed': True,
            },
        ),
        migrations.AlterUniqueTogether(
            name='sucursaltelefono',
            unique_together={('idsucursal', 'telefono')},
        ),
    ]
