# Generated by Django 2.0.1 on 2018-01-11 03:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0003_auto_20180111_0240'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('idproducto', models.ForeignKey(db_column='idproducto', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='inicio.Producto')),
                ('taquegoria', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'categoria',
                'managed': False,
            },
        ),
    ]
