# Generated by Django 2.0.1 on 2018-01-09 02:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inicio', '0003_producto_productoleyenda'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('taquiclave', models.BigIntegerField(primary_key=True, serialize=False)),
                ('email', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('nombre', models.CharField(blank=True, max_length=50, null=True)),
                ('apellidopaterno', models.CharField(blank=True, max_length=50, null=True)),
                ('apellidomaterno', models.CharField(blank=True, max_length=50, null=True)),
                ('municipio', models.CharField(blank=True, max_length=100, null=True)),
                ('colonia', models.CharField(blank=True, max_length=100, null=True)),
                ('calle', models.CharField(blank=True, max_length=100, null=True)),
                ('cp', models.IntegerField(blank=True, null=True)),
                ('numinterior', models.BigIntegerField(blank=True, null=True)),
                ('numexterior', models.BigIntegerField(blank=True, null=True)),
                ('fechaprimervista', models.DateField(blank=True, null=True)),
                ('numpuntos', models.BigIntegerField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'cliente',
                'managed': True,
            },
        ),
    ]
