# Generated by Django 2.0.1 on 2018-01-09 02:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0005_auto_20180109_0244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='cp',
            field=models.ForeignKey(db_column='cp', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='inicio.Cpedosucursal'),
        ),
    ]
