# Generated by Django 2.0.1 on 2018-01-12 01:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('taquiclave', models.BigIntegerField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=50, unique=True)),
                ('telefono', models.CharField(max_length=20)),
                ('nombre', models.CharField(max_length=50)),
                ('apellidopaterno', models.CharField(max_length=50)),
                ('apellidomaterno', models.CharField(max_length=50)),
                ('municipio', models.CharField(max_length=100)),
                ('colonia', models.CharField(max_length=100)),
                ('calle', models.CharField(max_length=100)),
                ('numinterior', models.BigIntegerField()),
                ('numexterior', models.BigIntegerField()),
                ('fechaprimervista', models.DateField()),
                ('numpuntos', models.BigIntegerField()),
            ],
            options={
                'db_table': 'cliente',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ContenerDjango',
            fields=[
                ('cantidad', models.BigIntegerField(blank=True, null=True)),
                ('idcontener', models.BigIntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'contener_django',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cpedocliente',
            fields=[
                ('cp', models.IntegerField(primary_key=True, serialize=False)),
                ('estado', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'cpedocliente',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cpedosucursal',
            fields=[
                ('cp', models.IntegerField(primary_key=True, serialize=False)),
                ('estado', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'cpedosucursal',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Fechapedpromo',
            fields=[
                ('fechapedido', models.DateField(primary_key=True, serialize=False)),
                ('promocion', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'fechapedpromo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('numpedido', models.BigIntegerField(primary_key=True, serialize=False)),
                ('metodopago', models.CharField(max_length=50)),
                ('preparado', models.BooleanField()),
                ('entregado', models.BooleanField()),
            ],
            options={
                'db_table': 'pedido',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('idproducto', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200, unique=True)),
                ('precio', models.FloatField()),
                ('descripcion', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'producto',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('idsucursal', models.BigIntegerField(primary_key=True, serialize=False)),
                ('horaapertura', models.DateTimeField()),
                ('horacierre', models.DateTimeField()),
                ('municipio', models.CharField(max_length=100)),
                ('colonia', models.CharField(max_length=100)),
                ('calle', models.CharField(max_length=100)),
                ('numinterior', models.BigIntegerField()),
                ('numexterior', models.BigIntegerField()),
            ],
            options={
                'db_table': 'sucursal',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('idproducto', models.ForeignKey(db_column='idproducto', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='inicio.Producto')),
                ('taquegoria', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'categoria',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Productoleyenda',
            fields=[
                ('idproducto', models.ForeignKey(db_column='idproducto', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='inicio.Producto')),
                ('leyenda', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'productoleyenda',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sucursaltelefono',
            fields=[
                ('idsucursal', models.ForeignKey(db_column='idsucursal', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='inicio.Sucursal')),
                ('telefono', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'sucursaltelefono',
                'managed': False,
            },
        ),
    ]
